name: instagram_colon
description: A Flutter Instagram Colon with Firebase and Riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.1.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.6
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  hooks_riverpod: ^2.1.1
  image: ^3.2.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  lottie: ^2.0.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  video_player: ^2.4.8
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/animations/
